
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-00
owner: ucsb-cs156-f24
repo_name: team02-f24-00
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-commit-edit-page","number":116,"title":"Pc commit edit page","url":"https://github.com/ucsb-cs156-f24/team02-f24-00/pull/116"},{"author":{"id":"U_kgDOBnFWcA","is_bot":false,"login":"raysujf","name":""},"headRefName":"Hongrui-UCSBOrganization","number":115,"title":"hs - Adding the UCSB Organization Table and Tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-00/pull/115"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-commit-index-page","number":114,"title":"Pc commit index page","url":"https://github.com/ucsb-cs156-f24/team02-f24-00/pull/114"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-create-commit-page","number":113,"title":"Pc create commit page","url":"https://github.com/ucsb-cs156-f24/team02-f24-00/pull/113"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-commit-placeholder-pages","number":112,"title":"pc - add placeholder pages for Index,Edit,Create for Commits","url":"https://github.com/ucsb-cs156-f24/team02-f24-00/pull/112"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-commit-table","number":111,"title":"Pc commit table","url":"https://github.com/ucsb-cs156-f24/team02-f24-00/pull/111"},{"author":{"id":"U_kgDOB3Dokw","is_bot":false,"login":"jenil-prajapati","name":""},"headRefName":"Jenil-RecommendationRequestsFixtures","number":75,"title":"jp - Create fixtures for RecommendationRequest","url":"https://github.com/ucsb-cs156-f24/team02-f24-00/pull/75"}]
