
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-00
owner: ucsb-cs156-f24
repo_name: team02-f24-00
pull_requests: [{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"sk-Articles-fixtures","number":123,"title":"Testing to See if chromatic error went away","url":"https://github.com/ucsb-cs156-f24/team02-f24-00/pull/123"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-commits-e2e-tests","number":122,"title":"Pc commits e2e tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-00/pull/122"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-commits-integration-tests","number":121,"title":"Pc commits integration tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-00/pull/121"},{"author":{"id":"U_kgDOBnFWcA","is_bot":false,"login":"raysujf","name":""},"headRefName":"Hongrui-UCSBOrganization","number":115,"title":"hs - Adding the UCSB Organization Table and Tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-00/pull/115"},{"author":{"id":"U_kgDOB3Dokw","is_bot":false,"login":"jenil-prajapati","name":""},"headRefName":"Jenil-RecommendationRequestsFixtures","number":75,"title":"jp - Create fixtures for RecommendationRequest","url":"https://github.com/ucsb-cs156-f24/team02-f24-00/pull/75"}]
