
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-staff
owner: ucsb-cs156-f24
repo_name: team02-staff
pull_requests: [{"author":{"id":"MDQ6VXNlcjcyODI0MjQ4","is_bot":false,"login":"sangitakunapuli","name":""},"headRefName":"sk-addArticlesFixtures","number":67,"title":"sk - Add fixtures for Articles","url":"https://github.com/ucsb-cs156-f24/team02-staff/pull/67"},{"author":{"id":"U_kgDOB3Dokw","is_bot":false,"login":"jenil-prajapati","name":""},"headRefName":"Jenil-RecommendationRequests","number":66,"title":"jp - Copy existing CRUD API RecommendationRequest from team02","url":"https://github.com/ucsb-cs156-f24/team02-staff/pull/66"},{"author":{"id":"U_kgDOBnFWcA","is_bot":false,"login":"raysujf","name":""},"headRefName":"Hongrui-UCSBOrganization","number":63,"title":"Copying backend CRUD API for UCSBOrganization from team01","url":"https://github.com/ucsb-cs156-f24/team02-staff/pull/63"}]
